### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by huangxiaoye** [lichunqiang/yii2-sweet-submit#1]
执行这个：composer require light\yii2-sweet-submit=*

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lightyii2-sweet-submit could not be found in any ver
sion, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det
  ails.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by lichunqiang** [comment]
试试:

```
composer require light/yii2-sweet-submit=~1.0.0
```

**Comment by huangxiaoye** [comment]
可以了，谢谢
